server:
  port: 20000
spring:
  application:
    name: AgentServer
  datasource:
    url: jdbc:mysql://mysql.server:3306/easy-agent?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false
    username: zhxx
    password: zhxx@123456
  prompt:
    max-step: 30

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
  mapper-locations: classpath:mapper/**.xml
