server:
  port: 20000

spring:
  application:
    name: AgentServer
  datasource:
    url: jdbc:mysql://mysql.server:3306/easy-agent?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false
    username: zhxx
    password: zhxx@123456
  prompt:
    max-step: 30

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      mapper-locations: classpath:mapper/**.xml

# 日志配置
logging:
  level:
    root: INFO
    io.github.hijun.agent: DEBUG
    org.springframework.web: DEBUG
    org.springframework.ai: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n'
